myuser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.StudentListView.as_view(), name='student_changelist'),
    path('add/', views.StudentCreateView.as_view(), name='student_add'),
    path('<int:pk>/', views.StudentUpdateView.as_view(), name='student_change'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('submit/',views.submit,name='submit'),
    path('success/',views.success,name='success')
   ]

user/models.py
from django.db import models

# Create your models here.
class College(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Branch(models.Model):
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    age = models.IntegerField(default=0, editable=True)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='0')
    phone_number = models.CharField(max_length=15, blank=True)
    mail_id = models.EmailField(blank=True)
    address = models.TextField(blank=True)
    college = models.ForeignKey(College, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name 

user/forms.py
from django import forms
from .models import Student, Branch

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'birthdate','age','gender','phone_number','mail_id','address', 'college','branch')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'college' in self.data:
            try:
                college_id = int(self.data.get('college'))
                self.fields['branch'].queryset = Branch.objects.filter(college_id=college_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.college.branch_set.order_by('name')

user/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Student, Branch
from .forms import StudentForm
from django.shortcuts import render,redirect

class StudentListView(ListView):
    model = Student
    form_class = StudentForm
    context_object_name = 'students'




class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('student_changelist')

class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm  
    success_url = reverse_lazy('student_changelist')

def load_branches(request):
    college_id = request.GET.get('college')
    branches = Branch.objects.filter(college_id=college_id).order_by('name')
    return render(request, 'user/branch_dropdown_list_options.html', {'branches': branches})




def register(request):
    if request.method == 'POST':
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        cpassword = request.POST.get('cpassword','')

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already in use")
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                return redirect('success')
        else:
            messages.info(request, "Passwords not matching")
            return redirect('register')
    return render(request, "register.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, "Invalid credentials")
            return redirect('login')
    return render(request, "login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def submit(request):
    return render(request,'submit.html')

def success(request):
    return render(request,'success.html')

templates/base.html
{% load static %}
<!doctype html>
<meta charset="utf-8">
    <title></title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  <head>
    <meta charset="utf-8">
    <title>E School Website</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    
  </head>
  <body>
    <h1></h1>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
      <a href="{% url 'student_changelist' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
          <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>School Store</h2>
      </a>
      <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav ms-auto p-4 p-lg-0">
              <a href="{% url 'student_changelist' %}" class="nav-item nav-link active">Home</a>

              <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Department</a>
                <div class="dropdown-menu fade-down m-0">
                    <div class="dropdown-content">
                        <a href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a>
                        <a href="https://en.wikipedia.org/wiki/Commerce">Commerce</a>
                        <a href="https://en.wikipedia.org/wiki/Mathematics">Mathematics</a>
                        <a href="https://en.wikipedia.org/wiki/Physics">Physics</a>
                        <a href="https://en.wikipedia.org/wiki/History">History</a>
                    </div>
                </div>
            </div>

  
              <div class="nav-item dropdown">
                  
                          {% if user.is_authenticated %}
                          Hi, {{ user.username }}
                          <div>
                              <a href="{% url 'logout' %}">Logout</a>
                          </div>
                          {% else %}
                          <div><a href="{% url 'register' %}">Register</a></div>
                          <div><a href="{% url 'login' %}">Login</a></div>
                          {% endif %}
                      </div>
                
          </div>
      </div>

  </nav>

    <a href="{% url 'student_add' %}" class="btn btn-primary btn-lg rounded-pill">
        Add Now <i class="fa fa-arrow-right ms-2"></i>
    </a>






    
    <hr>

    {% block content %}
    {% endblock %}
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f4f4f4;
        }

        .card {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            text-align: center;
        }

        h2 {
            color: #333;
        }

        input {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #06BBCC;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="card">
        <h2>Login</h2>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username"><br>
            <input type="password" name="password" placeholder="Password"><br>
            <input type="submit" value="Login" data-href-template="{% url 'student_add' %}"><br>
        </form>
    </div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Here</title>
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f4f4f4;
        }

        .card {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            text-align: center;
        }

        h2 {
            color: #333;
        }

        input {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #06BBCC;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        h3 {
            padding: 20px;
            color: black1;
        }
    </style>
</head>
<body>
    <div class="card">
        <h2>Registration</h2>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required><br>
            <input type="password" name="password" placeholder="Password" required><br>
            <input type="password" name="cpassword" placeholder="Confirm Password" required><br>
            <input type="submit" value="Register">




        </form>

        <h3>
            {% for msg in messages %}
                {{ msg }}
            {% endfor %}
        </h3>
    </div>
</body>
</html>

templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Submission Successful</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            padding: 20px;
        }

        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            margin: 0 auto;
        }

        h1 {
            color: #06BBCC;
        }

        p {
            color: #333;
            margin-bottom: 20px;
        }

        a {
            background-color: #06BBCC;
            color: white;
            border: none;
            padding: 10px 20px;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        a:hover {
            background-color: #06BBCC;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Order confirmed</h1>

        <a href="{% url 'demo' %}">Return to Home</a>
    </div>
</body>
</html>

templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Successful</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            padding: 20px;
        }

        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            margin: 0 auto;
        }

        h1 {
            color: #06BBCC;
        }

        p {
            color: #333;
            margin-bottom: 20px;
        }

        a {
            background-color: #06BBCC;
            color: white;
            border: none;
            padding: 10px 20px;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        a:hover {
            background-color: #06BBCC;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Registered Successfully</h1>
        <p>Thank you, {{ name }}, for Registering, login below to fill the application form</p>

        <a href="{% url 'login' %}">Login now</a>
    </div>
</body>
</html>

user/templates/user/branch_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

user/templates/user/student_form.html
{% extends 'base.html' %} {% block content %}

<h2>Register Here !!</h2>

<form
  method="post"
  id="studentForm"
  data-branches-url="{% url 'ajax_load_branches' %}"
  novalidate
>
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit">Submit</button>
  <a href="{% url 'logout' %}">Logout</a>
</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
  $("#id_college").change(function () {
    var url = $("#studentForm").attr("data-branches-url");
    var collegeId = $(this).val();

    $.ajax({
      url: url,
      data: {
        college: collegeId,
      },
      success: function (data) {
        $("#id_branch").html(data);
      },
    });
  });
</script>

{% endblock %}

user/templates/user/student_list.html
{% extends 'base.html' %}

{% block content %}
  <h2 style="text-center">Student Registration</h2>

  <p>
    <a href="{% url 'student_add' %}">Add Student</a>
  </p>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Birthdate</th>
        <th scope="col">Department</th>
        <th scope="col">Branch</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr>
          <td>
            <h5>{{ student.name }}</h5>
          </td>
          <td>{{ student.birthdate }}</td>
          <td>{{ student.college.name }}</td>
          <td>{{ student.branch.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">
            <a href="{% url 'student_add' %}">Add the first person</a>.
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <style>
    /* Increase the row height */
    table tbody tr {
      height: 50px; /* Adjust the value as needed */
    }

    /* Increase the column width */
    table tbody td {
      min-width: 150px; /* Adjust the value as needed */
    }
  </style>
{% endblock %}